apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dog-rescue-db
  namespace: dog-adoption
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: dog-rescue-db
  template:
    metadata:
      labels:
        app: dog-rescue-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: dog_rescue_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: init-db
          configMap:
            name: init-db
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

